"""M3: add documents and document chunks

Revision ID: 27e82d246b27
Revises: e1449d913f29
Create Date: 2026-08-27 16:05:55.312483
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27e82d246b27'
down_revision: Union[str, None] = 'e1449d913f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_incident_id'), 'documents', ['incident_id'], unique=False)
    op.create_index(op.f('ix_documents_service'), 'documents', ['service'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_incident_date'), 'document_chunks', ['incident_date'], unique=False)
    op.create_index(op.f('ix_document_chunks_section'), 'document_chunks', ['section'], unique=False)
    op.create_index(op.f('ix_document_chunks_service'), 'document_chunks', ['service'], unique=False)
    op.create_index('ix_document_chunks_service_section', 'document_chunks', ['service', 'section'], unique=False)
    op.create_index(op.f('ix_document_chunks_severity'), 'document_chunks', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_severity'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_service_section', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_service'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_section'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_incident_date'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_service'), table_name='documents')
    op.drop_index(op.f('ix_documents_incident_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
