"""create incidents table

Revision ID: e1449d913f29
Revises: 
Create Date: 2026-08-26 16:58:26.688185
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e1449d913f29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_incident_code'), 'incidents', ['incident_code'], unique=True)
    op.create_index(op.f('ix_incidents_incident_date'), 'incidents', ['incident_date'], unique=False)
    op.create_index(op.f('ix_incidents_service'), 'incidents', ['service'], unique=False)
    op.create_index('ix_incidents_service_severity', 'incidents', ['service', 'severity'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index('ix_incidents_service_severity', table_name='incidents')
    op.drop_index(op.f('ix_incidents_service'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_date'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_code'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
